[package]
name = "freeverb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
audio_module = {version = "0.1.0", path = "../audio_module" }
num_enum = {version = "0.7.4"}
strum = { version = "0.27.2"}
strum_macros = { version = "0.27.2"}
